version: '3'
services: 
  website:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./website
    volumes:
      - /app/node_modules
      - ./website:/app
  admin:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./admin
    volumes:
      - /app/node_modules
      - ./admin:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'