version: '3'
services: 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'website:website'
      - 'admin:admin'
  admin:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./admin
    volumes:
      - /app/node_modules
      - ./admin:/app
    ports:
      - '3001:3001'
    environment: 
      - NODE_ENV=development
      - PORT=3001
  website:
    stdin_open: true
    tty: true
    build:
      dockerfile: Dockerfile.dev
      context: ./website
    volumes:
      - /app/node_modules
      - ./website:/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development